apiVersion : apps/v1
kind: Deployment
metadata:
  name: japp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: japp
  template:
    metadata:
      labels:
        app: japp 
    spec:
      containers:
        - name: japp 
          image: webdevops.azurecr.io/japp
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: japp-service
  labels:
    app: japp
spec:
  type: LoadBalancer
  selector:
    app: japp
  ports:
    - port: 80
      targetPort: 80